version: '3.8'

services:

  app:
    build: .
    container_name: test-app

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: test-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb

    ports:
      - "3308:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: