spring:
  application:
    name: test

  datasource:
    url: jdbc:mysql://localhost:3308/testdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    #
jwt:
  secret : siuiamronaldo